### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by Cisco-the-wayword** [Jawad-Nazari/To-Do-List#6]
Hey Jawad,
- Your code looks great.✅
- Your code organization is top-notch.✅
- Your comments and variable names are very descriptive. ✅

- The code works perfectly when I run it on my local machine but the live demo link in the readme file doesn't work ❌

**Comment by Jawad-Nazari** [comment]
Hi @Cisco-the-wayword ,

Thanks for reviewing my code, I have updated the demo link. 🙏
